#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 17 14:40:59 2018

@author: zdhughes
"""



#global FAKE_CBLT
#global TIMED_FAKE_CBLT
#global EVENT_FAKE_CBLT
#global CONTINUOUS_FAKE_CBLT
#global CLOSE_SERVER

#global SERVER_CLOSED
#global SERVER_RENDEVOUS_DEFAULT
#global RENDEVOUS_PROCEED
#global RENDEVOUS_HALT

# =============================================================================
# FAKE_CBLT = 1
# TIMED_FAKE_CBLT = 2
# EVENT_FAKE_CBLT = 3
# CONTINUOUS_FAKE_CBLT = 4
# CLOSE_SERVER = 255
# 
# SERVER_CLOSED = 0
# SERVER_RENDEVOUS_DEFAULT = 255
# RENDEVOUS_PROCEED = 1
# RENDEVOUS_HALT = 0
# =============================================================================

CLEAR_EVENT = 200
SINGLE_CBLT = 201
TIMED_CBLT = 202
EVENT_CBLT = 203
CONTINUOUS_CBLT = 204
AUTOMATED_CBLT = 205
SINGLE_REREAD = 207
CLOSE_SERVER = 255

SERVER_CLOSED = 0
SERVER_RENDEVOUS_DEFAULT = 255
RENDEVOUS_PROCEED = 1
RENDEVOUS_HALT = 0


GET_DATA_WIDTH = 50
GET_DATA_OFFSET = 51
GET_AREA_WIDTH = 52
GET_AREA_OFFSET = 53
GET_REREAD_WIDTH = 54
GET_REREAD_OFFSET = 55
GET_HILO_WIDTH = 56
GET_HILO_OFFSET = 57
GET_CFD_THRESH = 58
GET_0_SUPRESS_LEVEL = 59
READ_ALL_PARAMS = 60
GET_FADC_MODE = 61

SET_DATA_WIDTH = 150
SET_DATA_OFFSET = 151
SET_AREA_WIDTH = 152
SET_AREA_OFFSET = 153
SET_REREAD_WIDTH = 154
SET_REREAD_OFFSET = 155
SET_HILO_WIDTH = 156
SET_HILO_OFFSET = 157
SET_CFD_THRESH = 158
SET_0_SUPRESS_LEVEL = 159
CLEAR_ALL_SCALARS = 160
SET_FADC_MODE = 161

#define CLEAR_EVENT 200
#define SINGLE_CBLT 201
#define TIMED_CBLT 202
#define EVENT_CBLT 203
#define CONTINUOUS_CBLT 204
#define AUTOMATED_CBLT 205
#define SINGLE_REREAD 207
#define CLOSE_SERVER 255